spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: springuser
    password: ThePassword
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: 'jpa-example:cache:'
      time-to-live: 86400s
  redis:
    host: localhost
    port: 6379
    database: 0
#  jpa:
#    hibernate:
#      ddl-auto: update
