spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: springuser
    password: ThePassword
#  jpa:
#    hibernate:
#      ddl-auto: update
